### ISSUE TITLE
Grafik Flowchart des Archivierungsprozesses fehlt

### ISSUE THREAD

**Issue by christiansievers** [dainst/ianus-web-content#5]
Hallo, wenn Sie auf der Seite "[Langzeitarchivierung](https://ianus-fdz.de/langzeitarchivierung)" die Abbildung "Flowchart des Archivierungsprozesses" hinzufügen (oder mir andersweitig zukommen lassen) könnten, wäre ich dankbar!

**Comment by juhly** [comment]
Hi, ich meine das müsste die Grafik sein? 
![Workflow_LZA-einfach_nichttechnisch_2015-09-15_Final_klein](https://user-images.githubusercontent.com/29372760/226925235-2a7a8871-a580-4252-b304-97f51b1eb692.png)

**Comment by christiansievers** [comment]
Sieht gut aus! Ich merke gerade, auf der Seite sind drei Nennungen von Flowcharts:
```
@todo fehlt? Flowchart des Transferprozesses bei IANUS © IANUS.
...
Flowchart des Einlieferungsprozesses bei IANUS © IANUS
...
Flowchart des Archivierungsprozesses bei IANUS © IANUS
```

Das hier könnte der Einlieferungsprozess sein. Um das zu beurteilen, müsste man die anderen beiden sehen. Ist das ein Fall von Datenarchäologie, die Grafiken zu finden? :)

**Comment by juhly** [comment]
Ja genau so sieht es aus! 

Ich bin gerade dabei mit einem Kollegen die Inhalte zu rekonstruieren... die einzelnen bilder sind da, ich muss mal schauen ob wir sie noch verwenden wollen da sich ja auch der prozess verändert (Kurator:innen werden nicht mehr so umfangreiche Arbeiten an den Daten vornehmen sondern eher die Datenersteller:innen z.B.)... aber ich werde sie erstmal einbinden bei der nächsten version.

**Comment by christiansievers** [comment]
oh wow. An so etwas arbeiten [wir](https://www.rsh-duesseldorf.de/musikhochschule/wir-ueber-uns/digi-kunstnrw/) auch gerade. Das ist sehr hilfreich, danke! Bei uns sollen auch die Einlieferer:innen selbst erfassen. Vielleicht unterhalten wir uns bei Gelegenheit mal darüber, wie diese Prozesse am besten ablaufen sollten?
